### ISSUE TITLE
patch.key-impl is wrong

### ISSUE THREAD

**Issue by yoursunny** [pollere/NDNpatches#2]
It seems that [patch.key-impl](https://github.com/pollere/NDNpatches/blob/c31ec7fea07a141ea990b310998c5a37113d2383/patch.key-impl) attempts to make ndn-cxx accept invalid objects written to its KeyChain, instead of properly recognize such objects.
This approach is wrong.

The structure of ndn-cxx KeyChain is an implementation detail. It is internal to ndn-cxx library.
ndn-ind and DCT library should not attempt to read or write any objects in the ndn-cxx KeyChain, but should store its object separately in another location (e.g. `$HOME/.ndn/ndn-ind-keychain`).
If necessary, they can interact with the ndn-cxx KeyChain using `ndnsec` or a helper program based on ndn-cxx APIs, but never access the files directly.

**Comment by kmnichols** [comment]
We have clarified the reason for this patch in the repo's README. However, we would like to further note that regardless of the bug that prompted them, your comments suggest a different role for "keychains" than we or current industry practice
assume.  We view keychains as an access-controlled container that holds security-related objects (certs, public and secret keys, CRLs, trust schemas, etc.).  In general, it's not the job of containers to stand in judgement over the objects they contain. In particular, secure applications *must* be responsible for validating the objects they use: they're the only ones with enough context to determine what "valid" *means* given their use case and threat model and even if they could convey this information to a third party like a keychain, the mechanics of third-party validation *vastly* increases the attack surface. 

Because of this, putting validation into a keychain (or anywhere else) is, at best, unnecessary and redundant.  More likely, it's a massive impediment to evolution. Take ndn-cxx as an example: It started by accepting two types of signing keys supported by 2010's OpenSSL, RSA & ECDSA, and those are still the only types supported today.  The youngest of these is more than 30 years old and both have been deprecated for more than a decade.  OpenSSL has evolved but whenever someone tries to add some of its more more modern crypto to ndn-cxx they discover that there are *dozens* of different places in the code that deeply believe they know exactly what it means for a key to be "valid" and would rather abort the entire process than let something new in the door. The end result is that nothing can change; what should be simple, incremental, evolution of a well-defined sub-system turns into endless bug chases through 60,000+ lines of spaghetti. The potential gain simply isn't worth the pain so nothing changes. 

We've been there: In our work to create DCT we are enabling the use of current-best-practice approaches and security code maintained by the security community like libsodium. The work to incorporate more modern practices exposed how difficult it is to add modern security code to the NDN libraries. Parts of DCT (some of which is not yet released) have been created to enable that since it's not clear to us that NDN's current model is fixable. Since we know first hand how much work all of this has been, we are making our work public hoping to assist others with an interest in secure data-centric communications.
